#!/home/rmc/progs/python/anaconda3/bin/python3

import sys
import os
import netCDF4 as nc
import time
import numpy as np
import xarray
from IPython import embed

args = sys.argv[1:]

if not args:
	print("Give me a netCDF file")
	os._exit(1)

if len(args) == 1:
	try:
		data = xarray.open_dataset(args[0])
	except FileNotFoundError:
		print("File not found " + args[0])
		os._exit(1)
else:
	data = []
	for a in args:
		try:
			data.append(xarray.open_dataset(a))
		except FileNotFoundError:
			print("File not found " + a)
			os._exit(1)

# define some utility functions
def timeof(val, units='seconds'):
	if units.startswith('seconds'):
		return time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(int(val)))
	elif units.startswith('hours'):
		return time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(int(val*3600)))
	elif units.startswith('days'):
		return time.strftime('%Y-%m-%d %H:%M:%S', time.gmtime(int(val*3600*24)))

embed(display_banner=False)
